# Generated by Django 4.1.7 on 2023-03-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types_h_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=255)),
            ],
        ),
    ]
